/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_library;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Choxmi
 */
public class Dashboard extends javax.swing.JFrame {
    JPanel[] panels;
    LibraryDAO library;
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        this.panels = new JPanel[]{pnlMember, pnlOps, pnlAuthor, pnlRegBook, pnlHelp};
        activatePanels(1);
        library = LibraryDAO.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMember = new javax.swing.JButton();
        btnOps = new javax.swing.JButton();
        btnAuthor = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        btnRegBooks = new javax.swing.JButton();
        pnlOps = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtBkCount = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtBkMemID = new javax.swing.JTextField();
        txtBkName1 = new javax.swing.JTextField();
        txtBk1Borrowed = new javax.swing.JTextField();
        txtBkName2 = new javax.swing.JTextField();
        txtBkQuantity = new javax.swing.JTextField();
        txtBkID1 = new javax.swing.JTextField();
        txtBk1Returned = new javax.swing.JTextField();
        txtBkID2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtBk2Borrowed = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtBk2Returned = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnBk1Borrow = new javax.swing.JButton();
        btnBk1Reserve = new javax.swing.JButton();
        btnBk2Borrow = new javax.swing.JButton();
        btnBk2Reserve = new javax.swing.JButton();
        btnBk1List = new javax.swing.JButton();
        btnBk2List = new javax.swing.JButton();
        btnBook1Return = new javax.swing.JButton();
        btnBk2Return = new javax.swing.JButton();
        btnBkSearch = new javax.swing.JButton();
        pnlMember = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMemID = new javax.swing.JTextField();
        txtMemFname = new javax.swing.JTextField();
        txtMemAddress = new javax.swing.JTextField();
        txtMemTel = new javax.swing.JTextField();
        txtMemLname = new javax.swing.JTextField();
        btnMemReg = new javax.swing.JButton();
        btnMemUpd = new javax.swing.JButton();
        btnMemSearch = new javax.swing.JButton();
        btnMemDel = new javax.swing.JButton();
        pnlRegBook = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtRegBkID = new javax.swing.JTextField();
        txtRegBkName = new javax.swing.JTextField();
        txtRegBkAuthor = new javax.swing.JTextField();
        txtRegBkDescription = new javax.swing.JTextField();
        btnRegBkAuthor = new javax.swing.JButton();
        btnRegBkReg = new javax.swing.JButton();
        btnRegBkSearch = new javax.swing.JButton();
        btnRegBkDel = new javax.swing.JButton();
        pnlAuthor = new javax.swing.JPanel();
        txtAuthName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAuthList = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        btnAuthSearch = new javax.swing.JButton();
        btnAuthAdd = new javax.swing.JButton();
        btnAuthReserve = new javax.swing.JButton();
        btnAuthBorrow = new javax.swing.JButton();
        lblAuthID = new javax.swing.JLabel();
        txtAuthID = new javax.swing.JTextField();
        pnlHelp = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMember.setText("Member");
        btnMember.setName("btnDashMember"); // NOI18N
        btnMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemberActionPerformed(evt);
            }
        });

        btnOps.setText("Transactions");
        btnOps.setName("btnDashBook"); // NOI18N
        btnOps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpsActionPerformed(evt);
            }
        });

        btnAuthor.setText("Author");
        btnAuthor.setName("btnDashAuthor"); // NOI18N
        btnAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthorActionPerformed(evt);
            }
        });

        btnHelp.setText("Help");
        btnHelp.setName("btnDashHelp"); // NOI18N
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        btnRegBooks.setText("Books");
        btnRegBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegBooksActionPerformed(evt);
            }
        });

        jLabel2.setText("Member ID");

        jLabel9.setText("Book1 Name");

        jLabel10.setText("Book2 Name");

        jLabel11.setText("Borrowed");

        txtBkCount.setText("Quantity");

        jLabel13.setText("Book1 ID");

        jLabel14.setText("Book2 ID");

        jLabel15.setText("Returned");

        jLabel16.setText("Borrowed");

        jLabel17.setText("Returned");

        jLabel12.setText("Book 1");

        jLabel18.setText("Book 2");

        btnBk1Borrow.setText("Borrow");

        btnBk1Reserve.setText("Reserve");

        btnBk2Borrow.setText("Borrow");

        btnBk2Reserve.setText("Reserve");

        btnBk1List.setText("jButton5");
        btnBk1List.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBk1ListActionPerformed(evt);
            }
        });

        btnBk2List.setText("jButton5");
        btnBk2List.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBk2ListActionPerformed(evt);
            }
        });

        btnBook1Return.setText("Return");

        btnBk2Return.setText("Return");

        btnBkSearch.setText("Search by Member");
        btnBkSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBkSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOpsLayout = new javax.swing.GroupLayout(pnlOps);
        pnlOps.setLayout(pnlOpsLayout);
        pnlOpsLayout.setHorizontalGroup(
            pnlOpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(pnlOpsLayout.createSequentialGroup()
                        .addGroup(pnlOpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlOpsLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBkMemID, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(txtBkCount)
                                .addGap(18, 18, 18)
                                .addComponent(txtBkQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlOpsLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(txtBkID1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBk1List, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(txtBkID2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBk2List, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlOpsLayout.createSequentialGroup()
                                .addGroup(pnlOpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(pnlOpsLayout.createSequentialGroup()
                                        .addComponent(btnBk1Borrow)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBk1Reserve)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnBook1Return))
                                    .addGroup(pnlOpsLayout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtBk1Returned, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlOpsLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtBkName1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlOpsLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtBk1Borrowed, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(pnlOpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlOpsLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBkName2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlOpsLayout.createSequentialGroup()
                                        .addComponent(btnBk2Borrow, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBk2Reserve)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBk2Return))
                                    .addGroup(pnlOpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlOpsLayout.createSequentialGroup()
                                            .addComponent(jLabel16)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtBk2Borrowed, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlOpsLayout.createSequentialGroup()
                                            .addComponent(jLabel17)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtBk2Returned, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap())))
            .addGroup(pnlOpsLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(78, 78, 78))
            .addGroup(pnlOpsLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(btnBkSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlOpsLayout.setVerticalGroup(
            pnlOpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlOpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBkCount)
                    .addComponent(txtBkMemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBkQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel18))
                .addGap(22, 22, 22)
                .addGroup(pnlOpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtBkID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtBkID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBk1List)
                    .addComponent(btnBk2List))
                .addGap(28, 28, 28)
                .addGroup(pnlOpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtBkName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtBkName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(pnlOpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtBk1Borrowed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtBk2Borrowed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(pnlOpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtBk1Returned, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtBk2Returned, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlOpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBk1Borrow)
                    .addComponent(btnBk1Reserve)
                    .addComponent(btnBk2Borrow)
                    .addComponent(btnBk2Reserve)
                    .addComponent(btnBook1Return)
                    .addComponent(btnBk2Return))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBkSearch)
                .addContainerGap())
        );

        pnlMember.setName("pnlMember"); // NOI18N

        jLabel1.setText("Member ID");

        jLabel3.setText("First Name");

        jLabel4.setText("Last Name");

        jLabel5.setText("Address");

        jLabel7.setText("Telephone");

        btnMemReg.setText("Register");
        btnMemReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemRegActionPerformed(evt);
            }
        });

        btnMemUpd.setText("Update");

        btnMemSearch.setText("Search");
        btnMemSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemSearchActionPerformed(evt);
            }
        });

        btnMemDel.setText("Delete");

        javax.swing.GroupLayout pnlMemberLayout = new javax.swing.GroupLayout(pnlMember);
        pnlMember.setLayout(pnlMemberLayout);
        pnlMemberLayout.setHorizontalGroup(
            pnlMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMemberLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMemberLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnMemReg)
                        .addGap(18, 18, 18)
                        .addComponent(btnMemUpd)
                        .addGap(18, 18, 18)
                        .addComponent(btnMemSearch)
                        .addGap(18, 18, 18)
                        .addComponent(btnMemDel)
                        .addContainerGap(73, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMemberLayout.createSequentialGroup()
                        .addGroup(pnlMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlMemberLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtMemTel))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMemberLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtMemFname, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMemberLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtMemID))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMemberLayout.createSequentialGroup()
                                .addGroup(pnlMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(pnlMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMemAddress)
                                    .addComponent(txtMemLname, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE))))
                        .addGap(89, 89, 89))))
        );
        pnlMemberLayout.setVerticalGroup(
            pnlMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMemberLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMemberLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(txtMemFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(txtMemLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMemberLayout.createSequentialGroup()
                        .addGroup(pnlMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(pnlMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlMemberLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel4)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel5))
                            .addComponent(txtMemAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(pnlMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMemTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(pnlMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMemReg)
                    .addComponent(btnMemUpd)
                    .addComponent(btnMemSearch)
                    .addComponent(btnMemDel))
                .addGap(104, 104, 104))
        );

        jLabel20.setText("Book ID");

        jLabel21.setText("Book Name");

        jLabel22.setText("Author");

        jLabel23.setText("Description");

        btnRegBkAuthor.setText("...");

        btnRegBkReg.setText("Register");
        btnRegBkReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegBkRegActionPerformed(evt);
            }
        });

        btnRegBkSearch.setText("Search");
        btnRegBkSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegBkSearchActionPerformed(evt);
            }
        });

        btnRegBkDel.setText("Delete");

        javax.swing.GroupLayout pnlRegBookLayout = new javax.swing.GroupLayout(pnlRegBook);
        pnlRegBook.setLayout(pnlRegBookLayout);
        pnlRegBookLayout.setHorizontalGroup(
            pnlRegBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegBookLayout.createSequentialGroup()
                .addGroup(pnlRegBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegBookLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(pnlRegBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22))
                        .addGap(34, 34, 34)
                        .addGroup(pnlRegBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRegBkName, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRegBkID, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRegBkDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlRegBookLayout.createSequentialGroup()
                                .addComponent(txtRegBkAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRegBkAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                    .addGroup(pnlRegBookLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(btnRegBkReg)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegBkSearch)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegBkDel)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        pnlRegBookLayout.setVerticalGroup(
            pnlRegBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegBookLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(pnlRegBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtRegBkID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pnlRegBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtRegBkName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnlRegBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtRegBkDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlRegBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtRegBkAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegBkAuthor))
                .addGap(55, 55, 55)
                .addGroup(pnlRegBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegBkReg)
                    .addComponent(btnRegBkSearch)
                    .addComponent(btnRegBkDel))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        tblAuthList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "BookID", "BookName", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAuthList);

        jLabel19.setText("Author");

        btnAuthSearch.setText("Search");
        btnAuthSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthSearchActionPerformed(evt);
            }
        });

        btnAuthAdd.setText("Add");
        btnAuthAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthAddActionPerformed(evt);
            }
        });

        btnAuthReserve.setText("Reserve");

        btnAuthBorrow.setText("Borrow");

        lblAuthID.setText("Author ID");

        javax.swing.GroupLayout pnlAuthorLayout = new javax.swing.GroupLayout(pnlAuthor);
        pnlAuthor.setLayout(pnlAuthorLayout);
        pnlAuthorLayout.setHorizontalGroup(
            pnlAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAuthorLayout.createSequentialGroup()
                .addGroup(pnlAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAuthorLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAuthorLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(pnlAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlAuthorLayout.createSequentialGroup()
                                .addComponent(lblAuthID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAuthID))
                            .addGroup(pnlAuthorLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(txtAuthName, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addComponent(btnAuthSearch)
                        .addGap(18, 18, 18)
                        .addComponent(btnAuthAdd)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAuthorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAuthReserve)
                .addGap(18, 18, 18)
                .addComponent(btnAuthBorrow)
                .addGap(28, 28, 28))
        );
        pnlAuthorLayout.setVerticalGroup(
            pnlAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAuthorLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(pnlAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAuthID)
                    .addComponent(txtAuthID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAuthName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(btnAuthSearch)
                    .addComponent(btnAuthAdd))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAuthReserve)
                    .addComponent(btnAuthBorrow))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlHelpLayout = new javax.swing.GroupLayout(pnlHelp);
        pnlHelp.setLayout(pnlHelpLayout);
        pnlHelpLayout.setHorizontalGroup(
            pnlHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );
        pnlHelpLayout.setVerticalGroup(
            pnlHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegBooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(pnlMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(111, 111, 111)
                    .addComponent(pnlOps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(111, 111, 111)
                    .addComponent(pnlRegBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(121, 121, 121)
                    .addComponent(pnlAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(111, 111, 111)
                    .addComponent(pnlHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMember)
                        .addGap(18, 18, 18)
                        .addComponent(btnOps)
                        .addGap(18, 18, 18)
                        .addComponent(btnAuthor)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegBooks)
                        .addGap(71, 71, 71)
                        .addComponent(btnHelp)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlOps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlRegBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pnlMember.getAccessibleContext().setAccessibleName("pnlMember");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemberActionPerformed
        activatePanels(0);
    }//GEN-LAST:event_btnMemberActionPerformed

    private void btnOpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpsActionPerformed
        activatePanels(1);
    }//GEN-LAST:event_btnOpsActionPerformed

    private void btnAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthorActionPerformed
        activatePanels(2);
    }//GEN-LAST:event_btnAuthorActionPerformed

    private void btnRegBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegBooksActionPerformed
        activatePanels(3);
    }//GEN-LAST:event_btnRegBooksActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        activatePanels(4);
    }//GEN-LAST:event_btnHelpActionPerformed

    private void btnMemRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemRegActionPerformed
        if(library.insertMember(txtMemFname.getText().toString(), txtMemLname.getText().toString(), txtMemAddress.getText().toString(), Integer.parseInt(txtMemTel.getText().toString())) == 1){
            System.out.println("It's a success");
            JOptionPane.showMessageDialog(null, "Member Registered");
        }else{
            System.out.println("It's been failed:(");
            JOptionPane.showMessageDialog(null, "Member registration failed");
        }
    }//GEN-LAST:event_btnMemRegActionPerformed

    private void btnMemSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemSearchActionPerformed
        int key = 0;
        List<String> columns = new ArrayList<>();
        List<String> values = new ArrayList<>();
        ResultSet result;
        if(txtMemID.getText().toString()!=""){
            key = tryParse(txtMemID.getText().toString());
        }
        
        if(!txtMemFname.getText().toString().equals("")){
            columns.add("mem_first_name");
            values.add(txtMemFname.getText().toString());
        }
        
        if(!txtMemLname.getText().toString().equals("")){
            columns.add("mem_last_name");
            values.add(txtMemLname.getText().toString());
        }
        
        result = library.searchRecords("members","mem_id",key, columns, values,"");
        ResultSetMetaData rsmd;
        int columnsNumber;
        try {
            rsmd = result.getMetaData();
            columnsNumber = rsmd.getColumnCount();
        
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        ResultsetHolder.setResults(result,"Mem");
        ModalDialog resDialog = new ModalDialog(this, true);
        resDialog.setVisible(true);
    }//GEN-LAST:event_btnMemSearchActionPerformed

    private void btnAuthAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthAddActionPerformed
        if(library.insertAuthor(txtAuthName.getText().toString()) == 1){
            System.out.println("Insertion Success");
            JOptionPane.showMessageDialog(null, "Author Registered");
        }else{
            System.out.println("Insertion failed");
            JOptionPane.showMessageDialog(null, "Author Registration failed");
        }
    }//GEN-LAST:event_btnAuthAddActionPerformed

    private void btnAuthSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthSearchActionPerformed
        int key = 0;
        List<String> columns = new ArrayList<>();
        List<String> values = new ArrayList<>();
        ResultSet result;
        if(lblAuthID.getText().toString()!=""){
            key = tryParse(lblAuthID.getText().toString());
        }
        if(txtAuthName.getText().toString()!=""){
            columns.add("auth_Name");
            values.add(txtAuthName.getText().toString());
        }
        
        result = library.searchRecords("author","auth_id",key, columns, values,"");
        ResultsetHolder.setResults(result,"Auth");
        ModalDialog resDialog = new ModalDialog(this, true);
        resDialog.setVisible(true);
        
    }//GEN-LAST:event_btnAuthSearchActionPerformed

    private void btnRegBkRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegBkRegActionPerformed
        int auth = tryParse(txtRegBkAuthor.getText().toString());
        if(library.insertBook(txtRegBkName.getText().toString(), txtRegBkDescription.getText().toString(), auth) == 1){
            System.out.println("Book Added");
            JOptionPane.showMessageDialog(null, "Book Registered");
        }else{
            System.out.println("Book add failed");
            JOptionPane.showMessageDialog(null, "Registration failed");
        }
    }//GEN-LAST:event_btnRegBkRegActionPerformed

    private void btnRegBkSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegBkSearchActionPerformed
        int key = 0;
        List<String> columns = new ArrayList<>();
        List<String> values = new ArrayList<>();
        ResultSet result;
        if(txtRegBkID.getText().toString()!=""){
            key = tryParse(txtRegBkID.getText().toString());
        }
        
        if(!txtRegBkName.getText().toString().equals("")){
            columns.add("bk_name");
            values.add(txtRegBkName.getText().toString());
        }
        
        if(!txtRegBkAuthor.getText().toString().equals("")){
            columns.add("bk_author");
            values.add(txtRegBkAuthor.getText().toString());
        }
        
        result = library.searchRecords("books","bk_id",key, columns, values,"");
        ResultsetHolder.setResults(result,"Book");
        ModalDialog resDialog = new ModalDialog(this, true);
        resDialog.setVisible(true);
    }//GEN-LAST:event_btnRegBkSearchActionPerformed

    private void btnBkSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBkSearchActionPerformed
        int key = 0;
        List<String> columns = new ArrayList<>();
        List<String> values = new ArrayList<>();
        ResultSet result;
        if(txtBkMemID.getText().toString()!=""){
            key = tryParse(txtBkMemID.getText().toString());
        }
        
        result = library.searchRecords("members","mem_id",key, columns, values,"");
        ResultsetHolder.setResults(result,"Ops_Mem");
        ModalDialog resDialog = new ModalDialog(this, true);
        resDialog.setVisible(true);
    }//GEN-LAST:event_btnBkSearchActionPerformed

    private void btnBk1ListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBk1ListActionPerformed
        int key = 0;
        List<String> columns = new ArrayList<>();
        List<String> values = new ArrayList<>();
        ResultSet result;
        result = library.searchRecords("books","bk_id",key, columns, values,"");
        ResultsetHolder.setResults(result,"Book1_List");
        ModalDialog resDialog = new ModalDialog(this, true);
        resDialog.setVisible(true);
    }//GEN-LAST:event_btnBk1ListActionPerformed

    private void btnBk2ListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBk2ListActionPerformed
        int key = 0;
        List<String> columns = new ArrayList<>();
        List<String> values = new ArrayList<>();
        ResultSet result;
        result = library.searchRecords("books","bk_id",key, columns, values,"");
        ResultsetHolder.setResults(result,"Book2_List");
        ModalDialog resDialog = new ModalDialog(this, true);
        resDialog.setVisible(true);
    }//GEN-LAST:event_btnBk2ListActionPerformed

    private void activatePanels(int type){
        for(int i = 0;i<panels.length;i++){
            if(type!=i){
                panels[i].setVisible(false);
            }else{
                panels[i].setVisible(true);
            }
        }
    }
    
    private int tryParse(String txt){
        int val = 0;
        try{
            val = Integer.parseInt(txt);
        }catch(Exception e){
            val = 0;
        }
        return val;
    }
    
    private void processExtra(String book_id, String mem_id,int step){
        int key = 0;
        List<String> columns = new ArrayList<>();
        List<String> values = new ArrayList<>();
        ResultSet result;
        if(book_id!=""){
            key = tryParse(book_id);
        }
        
        if(key!=0){
            result = library.searchRecords("books","bk_id",key, columns, values,"");
            ResultsetHolder.setResults(result,"Ops_Bk_"+step);
            setColumns();
            
            if(book_id!=""){
                key = tryParse(book_id);
            }
            
            if(key > 0){
                columns.clear();
                values.clear();
                columns.add("trns_bk_id");
                columns.add("trns_mem_id");
                values.add(book_id);
                values.add(mem_id);
                result = library.searchRecords("transactions","trns_id",key, columns, values," ORDER BY trns_id DESC");
                ResultsetHolder.setResults(result,"Trns_"+step);
            }
        }
    }
    
    public void setColumns(){
        List<String> records = ResultsetHolder.getRecord();
        switch(ResultsetHolder.modalType){
            case "Mem":
                txtMemID.setText(records.get(0));
                txtMemFname.setText(records.get(1));
                txtMemLname.setText(records.get(2));
                txtMemAddress.setText(records.get(3));
                txtMemTel.setText(records.get(4));
                break;
            case "Auth":
                txtAuthID.setText(records.get(0));
                txtAuthName.setText(records.get(1));
                break;
            case "Book":
                txtRegBkID.setText(records.get(0));
                txtRegBkName.setText(records.get(1));
                txtRegBkDescription.setText(records.get(2));
                txtRegBkAuthor.setText(records.get(3));
                break;
            case "Ops_Mem":
                txtBkID1.setText(records.get(6));
                txtBkID2.setText(records.get(7));
                processExtra(txtBkID1.getText().toString(),txtBkMemID.getText().toString(),1);
                processExtra(txtBkID2.getText().toString(),txtBkMemID.getText().toString(),2);
                break;
            case "Ops_Bk_1":
                txtBkName1.setText(records.get(1));
                break;
            case "Ops_Bk_2":
                txtBkName2.setText(records.get(1));
                break;
            case "Trns_1":
                txtBk1Borrowed.setText(records.get(3));
                txtBk1Returned.setText(records.get(4));
                break;
            case "Trns_2":
                txtBk2Borrowed.setText(records.get(3));
                txtBk2Returned.setText(records.get(4));
                break;
            case "Book1_List":
                txtBkID1.setText(records.get(0));
                txtBkName1.setText(records.get(1));
                break;
            case "Book2_List":
                txtBkID2.setText(records.get(0));
                txtBkName2.setText(records.get(1));
                break;
            default:
                break;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus losok and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAuthAdd;
    private javax.swing.JButton btnAuthBorrow;
    private javax.swing.JButton btnAuthReserve;
    private javax.swing.JButton btnAuthSearch;
    private javax.swing.JButton btnAuthor;
    private javax.swing.JButton btnBk1Borrow;
    private javax.swing.JButton btnBk1List;
    private javax.swing.JButton btnBk1Reserve;
    private javax.swing.JButton btnBk2Borrow;
    private javax.swing.JButton btnBk2List;
    private javax.swing.JButton btnBk2Reserve;
    private javax.swing.JButton btnBk2Return;
    private javax.swing.JButton btnBkSearch;
    private javax.swing.JButton btnBook1Return;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnMemDel;
    private javax.swing.JButton btnMemReg;
    private javax.swing.JButton btnMemSearch;
    private javax.swing.JButton btnMemUpd;
    private javax.swing.JButton btnMember;
    private javax.swing.JButton btnOps;
    private javax.swing.JButton btnRegBkAuthor;
    private javax.swing.JButton btnRegBkDel;
    private javax.swing.JButton btnRegBkReg;
    private javax.swing.JButton btnRegBkSearch;
    private javax.swing.JButton btnRegBooks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAuthID;
    private javax.swing.JPanel pnlAuthor;
    private javax.swing.JPanel pnlHelp;
    private javax.swing.JPanel pnlMember;
    private javax.swing.JPanel pnlOps;
    private javax.swing.JPanel pnlRegBook;
    private javax.swing.JTable tblAuthList;
    private javax.swing.JTextField txtAuthID;
    private javax.swing.JTextField txtAuthName;
    private javax.swing.JTextField txtBk1Borrowed;
    private javax.swing.JTextField txtBk1Returned;
    private javax.swing.JTextField txtBk2Borrowed;
    private javax.swing.JTextField txtBk2Returned;
    private javax.swing.JLabel txtBkCount;
    private javax.swing.JTextField txtBkID1;
    private javax.swing.JTextField txtBkID2;
    private javax.swing.JTextField txtBkMemID;
    private javax.swing.JTextField txtBkName1;
    private javax.swing.JTextField txtBkName2;
    private javax.swing.JTextField txtBkQuantity;
    private javax.swing.JTextField txtMemAddress;
    private javax.swing.JTextField txtMemFname;
    private javax.swing.JTextField txtMemID;
    private javax.swing.JTextField txtMemLname;
    private javax.swing.JTextField txtMemTel;
    private javax.swing.JTextField txtRegBkAuthor;
    private javax.swing.JTextField txtRegBkDescription;
    private javax.swing.JTextField txtRegBkID;
    private javax.swing.JTextField txtRegBkName;
    // End of variables declaration//GEN-END:variables
}
